name = "my-r2-explorer"
compatibility_date = "2024-11-06"
main = "index.ts"
workers_dev = true
assets = { directory = "../../dashboard/dist/spa", binding = "ASSETS", html_handling = "auto-trailing-slash", not_found_handling = "single-page-application", run_worker_first = ["/api/*", "/share/*"] }

[[r2_buckets]]
binding = 'teste'
bucket_name = 'teste'
preview_bucket_name = 'teste'

